//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainWebServices.IsAdminReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IsAdminReference.IIsAdmin")]
    public interface IIsAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIsAdmin/IsUserAdmin", ReplyAction="http://tempuri.org/IIsAdmin/IsUserAdminResponse")]
        bool IsUserAdmin(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIsAdmin/IsUserAdmin", ReplyAction="http://tempuri.org/IIsAdmin/IsUserAdminResponse")]
        System.Threading.Tasks.Task<bool> IsUserAdminAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIsAdminChannel : DomainWebServices.IsAdminReference.IIsAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsAdminClient : System.ServiceModel.ClientBase<DomainWebServices.IsAdminReference.IIsAdmin>, DomainWebServices.IsAdminReference.IIsAdmin {
        
        public IsAdminClient() {
        }
        
        public IsAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsUserAdmin(int userId) {
            return base.Channel.IsUserAdmin(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAdminAsync(int userId) {
            return base.Channel.IsUserAdminAsync(userId);
        }
    }
}
