//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainWebServices.GetUserIdReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetUserIdReference.IGetUserId")]
    public interface IGetUserId {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetUserId/GetExistingUserId", ReplyAction="http://tempuri.org/IGetUserId/GetExistingUserIdResponse")]
        int GetExistingUserId(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetUserId/GetExistingUserId", ReplyAction="http://tempuri.org/IGetUserId/GetExistingUserIdResponse")]
        System.Threading.Tasks.Task<int> GetExistingUserIdAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetUserIdChannel : DomainWebServices.GetUserIdReference.IGetUserId, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserIdClient : System.ServiceModel.ClientBase<DomainWebServices.GetUserIdReference.IGetUserId>, DomainWebServices.GetUserIdReference.IGetUserId {
        
        public GetUserIdClient() {
        }
        
        public GetUserIdClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetUserIdClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetUserIdClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetUserIdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetExistingUserId(string username, string password) {
            return base.Channel.GetExistingUserId(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetExistingUserIdAsync(string username, string password) {
            return base.Channel.GetExistingUserIdAsync(username, password);
        }
    }
}
