//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainWebServices.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDecryptData")]
    public interface IDecryptData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptData/Decrypt", ReplyAction="http://tempuri.org/IDecryptData/DecryptResponse")]
        string Decrypt(string clearText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptData/Decrypt", ReplyAction="http://tempuri.org/IDecryptData/DecryptResponse")]
        System.Threading.Tasks.Task<string> DecryptAsync(string clearText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecryptDataChannel : DomainWebServices.ServiceReference1.IDecryptData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptDataClient : System.ServiceModel.ClientBase<DomainWebServices.ServiceReference1.IDecryptData>, DomainWebServices.ServiceReference1.IDecryptData {
        
        public DecryptDataClient() {
        }
        
        public DecryptDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Decrypt(string clearText) {
            return base.Channel.Decrypt(clearText);
        }
        
        public System.Threading.Tasks.Task<string> DecryptAsync(string clearText) {
            return base.Channel.DecryptAsync(clearText);
        }
    }
}
